### ISSUE TITLE
secondary structure input

### ISSUE THREAD

**Issue by kad-ecoli** [seqan/lara#2] opened 2021-10-25 15:24 UTC
In https://github.com/seqan/lara, it was stated that LaRA2 "can read many input formats for RNA structure, e.g. Dot-bracket notation, Stockholm, Vienna format". However, I cannot find an option in lara2 that accepts dot bracket notation. It seems it only accepts RNAfold format dot plot in .ps format. Is there a way to input dot bracket notation instead?

**Comment by kad-ecoli** [comment] 2021-10-25 15:29
In fact, lara2 does not seem to work with RNAfold format dot plot either

```
$ ../RNAfold --version
RNAfold 2.4.18
$ ../RNAfold input1.fasta
>7mqaL2
GACUAUACUUUCAGGGAUCAUAGUGUGUUACUAAACCACGAGGAAGAGAGGUAGCGUUUUCUCCUGAGCGUGAAGCCGGCUUUCUGGCGUUGCUUGGCUGCAACUGCCGUCAGCCAUUGAUGAUCGUUCUUCUCUCCGUAUUGGGGAGUGAGAGGGAGAGAACGCGGUCUGAGUGGU
(((.(((((............)))))))).....(((((..(((.........((((((((((((((.(((.((...((((..(.((((((((......))))).))))..)))).)).))).))..((((((((((.....)))))).))))))))))))))))..)))..))))) (-61.50)
$ ../RNAfold input2.fasta
>6az33
AGUGGUAAUGCGAAACACUGCCAGGUAACAAAUCAAUCCUCCCACGGUGAGCUUUCUUUUCACCAUAAUCCACCUUGGGCCUUUUACCGCGUUGUUCGGAGCGGGGGCUCAAGAUUGAAAAAUGCAGCUCUACGUACUGUUGUGAGUUCUGCGCAUUAACGCAAAAACCUGGGGUGU
..............(((((.((((((...................((((((.......)))))).........(((((((((....((((..........))))))))))))).(((...(((((.((...((.(((....))).))...)))))))....)))..))))))))))) (-50.80)
$ ../lara -d 7mqaL2_ss.ps -d 6az33_ss.ps
GACUAUACUUUCAGGGAUCAUAGUGUGUUACUAAACCACGAGGAAGAGAGGUAGCGUUUUCUCCUGAGCGUGAAGCCGGCUUUCUGGCGUUGCUUGGCUGCAACUGCCGUCAGCCAUUGAUGAUCGUUCUUCUCUCCGUAUUGGGGAGUGAGAGGGAGAGAACGCGGUCUGAGUGGU
/home/cz378/Program/LARA/lara/include/seqan/include/seqan/basic/basic_exception.h:363 FAILED!  (Uncaught exception of type std::runtime_error: WARNING: No structure information found in file 7mqaL2_ss.ps)

stack trace:
  0                      [0x4efd2f]
  1                      [0x40cbbe]
  2                      [0x512e9c]
  3                      [0x512f07]
  4                      [0x513069]
  5                      [0x40aad8]
  6                      [0x4e1517]
  7                      [0x412639]
  8                      [0x5d9650]
  9                      [0x41b55e]

Aborted
```

**Comment by joergi-w** [comment] 2021-10-26 09:04
Hi, thanks for asking! In fact, LaRA works as intended and I can provide you some help with these input files:

1. All the listed input formats (except dot plot) are passed with the -i (or a second file with -j) parameter. The differentiation among the formats is based on the filename's suffix: Use `.dbn` for dot-bracket notation, `.dbv` for vienna format, `.sth` for Stockholm, `.ct` for Connect, and `.bpseq` for bpseq file input.
2. For the dot plot format, you must execute RNAfold with the `-p` parameter to calculate the partition function. You retrieve additional output files, in your example `7mqaL2_dp.ps` and `6az33_dp.ps`. Note the `_dp` infix in the filename.

Please let me know if this solves your problem, and I'll see if I can improve the documentation.

**Comment by kad-ecoli** [comment] 2021-10-26 19:41
I am still not able to use lara with ``.dbn`` files.
For example. if LARA was compiled without ViennaRNA:

```
$ cat input.dbn
>7mqaL2
GACUAUACUUUCAGGGAUCAUAGUGUGUUACUAAACCACGAGGAAGAGAGGUAGCGUUUUCUCCUGAGCGUGAAGCCGGCUUUCUGGCGUUGCUUGGCUGCAACUGCCGUCAGCCAUUGAUGAUCGUUCUUCUCUCCGUAUUGGGGAGUGAGAGGGAGAGAACGCGGUCUGAGUGGU
(((.(((((............)))))))).....(((((..(((.........((((((((((((((.(((.((...((((..(.((((((((......))))).))))..)))).)).))).))..((((((((((.....)))))).))))))))))))))))..)))..)))))
>6az33
AGUGGUAAUGCGAAACACUGCCAGGUAACAAAUCAAUCCUCCCACGGUGAGCUUUCUUUUCACCAUAAUCCACCUUGGGCCUUUUACCGCGUUGUUCGGAGCGGGGGCUCAAGAUUGAAAAAUGCAGCUCUACGUACUGUUGUGAGUUCUGCGCAUUAACGCAAAAACCUGGGGUGU
..............(((((.((((((...................((((((.......)))))).........(((((((((....((((..........))))))))))))).(((...(((((.((...((.(((....))).))...)))))))....)))..)))))))))))
$ lara -i input.dbn 
Cannot compute a structure without the ViennaRNA library. Please install ViennaRNA and try again.
```

**Comment by kad-ecoli** [comment] 2021-10-26 19:58
It seems although LARA technically can read the dbn file, it only parses the sequence but not the secondary structure from the dbn file.

**Comment by joergi-w** [comment] 2021-11-01 08:31
LaRA needs more than a fixed structure to compute a good structural alignment, and even if you provide a dot-bracket structure, LaRA attempts to calculate the base pairing probabilities with ViennaRNA. A dbn file would just allow a single possible structure which is too restrictive in most cases. 
Would you like to compute such alignments anyway? If yes, what is the use case?

**Comment by kad-ecoli** [comment] 2021-11-01 13:34
One of the most obvious scenario is when the secondary structure was experimentally determined. On average, ViennaRNA RNAfold predicted secondary structure only has <70% overlap with experimentally determined secondary structure. In this particular case, more accurate pairwise alignment could potentially be generated using the more accurate experimental secondary structure than many less accurate RNAfold predicted secondary structures.

**Comment by joergi-w** [comment] 2021-11-04 13:06
Thanks, I agree that this is a good reason. You can input these fixed structures now (if you use the newest commit) and the given interactions are considered with a score of 10 for the alignment. Note that you can still adapt the impact of the structure score with the -b option: it is a factor, e.g. b=2 sets the structural score to 20, and b<1 decreases the structure importance.

**Comment by joergi-w** [comment] 2021-12-06 10:36
I assume that it is solved, so I'm closing this issue.

**Closed as completed by joergi-w** 2021-12-06 10:36 UTC
Labels: help wanted

**Comment by kad-ecoli** [comment] 2021-12-13 18:15
Yes, the issue is solved. Thank you.
